project:
  type: website

# execute:
#   freeze: auto # re-render only changed chapters

website:
  title: "MSc Medical Biometry/Biostatistics"
  sidebar:
    - id: exercises
      title: "MSc Medical Biometry/Biostatistics"
      style: "floating"
      logo: image002.png
      collapse-level: 2
      align: left
      contents:
        - section: "Statistik Vorkurs"
          href: exercises/precourse.rmd
          contents:
            - exercises/block1.rmd
            - exercises/block2.rmd
            - exercises/block3.rmd
            - exercises/block4.rmd
            - exercises/block5.rmd
            - exercises/block6.rmd
            - exercises/block7.rmd
            - exercises/block8.rmd
            - exercises/final1_5.rmd
        - section: "Biometrie I"
          href: exercises/biometrie_I.rmd
          contents:
            - exercises/biometrie_1.rmd
            - exercises/biometrie_2.rmd
            - exercises/biometrie_3.rmd
            - exercises/biometrie_4.rmd
            - exercises/biometrie_5.rmd
            - exercises/biometrie_6.rmd
            - exercises/biometrie_7.rmd
            - exercises/biometrie_8.rmd
            - exercises/biometrie_9.rmd


html:
  css: out/webex.css
  include-after-body: out/webex.js

format:
  html:
    theme: cosmo  
    toc: true
    css:
      - include/webex.css
    include-after-body:
      - include/webex.js
