---
title: Block 6
---
```{r, echo = FALSE, results='asis'}
library(webexercises)
```

## Matrizen

### Übungen 6 – A1

::: {.webex-check .webex-box}
```{r, results='asis', echo=FALSE}
opts <- c(
	"$A \\cdot B = \\begin{pmatrix} 2 & 3 & -1 \\\\\\ 1 & 0 & -1 \\\\\\ 2 & -6 & 8 \\end{pmatrix}\\\\$
	$A^{T} = \\begin{pmatrix} 2 & 0 & 1 \\\\\\ -2 & 1 & 2 \\\\\\ 0 & -1 & -3 \\end{pmatrix}$ <br><br>
	$\\\\ B^{T} = \\begin{pmatrix} 0 & 1 & 0 \\\\\\ 2 & 2 & -1 \\\\\\ -2 & -3 & 1 \\end{pmatrix}$ <br><br>
	$B^{T} \\cdot A^{T} = (AB)^{T} = \\begin{pmatrix} -2 & 1 & 2 \\\\\\ -6 & 0 & -3 \\\\\\ 8 & -1 & 1 \\end{pmatrix}$ <br><br><br><br> ",

	answer = "$A \\cdot B = \\begin{pmatrix} 2 & -3 & 1 \\\\\\ 1 & 0 & -1 \\\\\\ -2 & -6 & 8 \\end{pmatrix}\\\\$
	$A^{T} = \\begin{pmatrix} 1 & 0 & 2 \\\\\\ 2 & 1 & -2 \\\\\\ -3 & -1 & 0 \\end{pmatrix}$ <br><br>
	$\\\\B^{T} = \\begin{pmatrix} 0 & 1 & 0 \\\\\\ -1 & 2 & 2 \\\\\\ 1 & -3 & -2 \\end{pmatrix}$ <br><br>
	$B^{T} \\cdot A^{T} = (AB)^{T} = \\begin{pmatrix} 2 & 1 & -2 \\\\\\ -3 & 0 & -6 \\\\\\ 1 & -1 & 8 \\end{pmatrix}$<br><br><br><br>",

	"$A \\cdot B = \\begin{pmatrix} 2 & -3 & -1 \\\\\\ 1 & 0 & -1 \\\\\\ 2 & -6 & 8 \\end{pmatrix}\\\\$
	$A^{T} = \\begin{pmatrix} -3 & -1 & 0 \\\\\\ 2 & 1 & -2 \\\\\\ 1 & 0 & 2 \\end{pmatrix}$ <br><br>
	$\\\\B^{T} = \\begin{pmatrix} 1 & -3 & -2 \\\\\\ -1 & 2 & 2 \\\\\\ 0 & 1 & 0 \\end{pmatrix}$ <br><br>
	$B^{T} \\cdot A^{T} = (AB)^{T} = \\begin{pmatrix} 1 & -1 & 8 \\\\\\ -3 & 0 & -6 \\\\\\ 2 & 1 & -2 \\end{pmatrix}$ <br><br>"
)
cat("(a) Gegeben seien die beiden Matrizen <br> <br>
	$A =\\begin{pmatrix} 1 & 2 & -3 \\\\\\ 0 & 1 & -1 \\\\\\ 2 & -2 & 0 \\\\\\ \\end{pmatrix}$ und $B =\\begin{pmatrix} 0 & -1 & 1 \\\\\\ 1 & 2 & -3 \\\\\\ 0 & 2 & -2 \\\\\\ \\end{pmatrix}$.
	<br><br> Berechnen Sie A · B, $A^{T}$, $B^{T}$, sowie $B^{T}$ $\\cdot$ $A^{T}$.<br><br>",
	longmcq(opts))
```
:::

::: {.callout-tip collapse="true" title="Lösung"}
$$ AB = \begin{pmatrix}2 & -3 & 1\\ 1 & 0 & -1\\ -2 & -6 & 8 \end{pmatrix}$$
$$ A^{T} = \begin{pmatrix}1 & 0 & 2\\ 2 & 1 & -2\\ -3 & -1 & 0 \end{pmatrix}$$
$$ B^{T} = \begin{pmatrix}0 & 1 & 0\\ -1 & 2 & 2\\ 1 & -3 & -2 \end{pmatrix}$$
$$ B^{T}A^{T} = (AB)^{T} = \begin{pmatrix}2 & 1 & -2\\ -3 & 0 & -6\\ 1 & -1 & 8 \end{pmatrix}$$
:::

### Übungen 6 – A2
::: {.webex-check .webex-box}
```{r, results='asis', echo=FALSE}
cat("(a) Berechnen Sie <br> <br> $A =\\begin{pmatrix} -4 & -3 & 2 & 0 \\\\\\ 1 & 2 & -2 & 2 \\\\\\ 0 & 3 & 1 & -1 \\\\\\ 4 & 5 & 0 & 7 \\end{pmatrix}$ $\\begin{pmatrix} 1 \\\\\\ 1 \\\\\\ 0 \\\\\ 1 \\end{pmatrix} =$<br><br>")
cat("$A = \\biggl($", paste0(fitb(-7, num=TRUE), fitb(5, num=TRUE), fitb(2, num=TRUE), fitb(16, num=TRUE)), "$\\biggl)$")	

```
:::

::: {.callout-tip collapse="true" title="Lösung"}
(a) $$ \begin{pmatrix}-4 & -3 & 2 & 0 \\ 1 & 2 & -2 & 2 \\ 0 & 3 & 1 & -1 \\ 4 & 5 & 0 & 7 \end{pmatrix}\begin{pmatrix}1 \\ 1 \\ 0 \\ 1\end{pmatrix} = \begin{pmatrix}-7 \\ 5 \\ 2 \\ 16 \end{pmatrix}$$
:::

::: {.webex-check .webex-box}
```{r, results='asis', echo=FALSE}
opts <- c(
	"$\\begin{pmatrix} 4x & + & 3y & + & 2z \\\\\\ & & y & - & z \\\\\\ 2x & + & y\\end{pmatrix}$<br><br>",

	answer = "$\\begin{pmatrix} 4x & - & 3y & + & 2z \\\\\\ & & y & - & z \\\\\\ -2x & + & 3y\\end{pmatrix}$<br><br>",

	"$\\begin{pmatrix} 4x & + & 3y & - & 2z \\\\\\ x & - & y \\\\\\ -2x & + & y\\end{pmatrix}$"
)
cat("(b) Berechnen Sie <br> <br> $A =\\begin{pmatrix} 4 & -3 & 2 \\\\\\ 0 & 1 & -1 \\\\\\ -2 & 3 & 0 \\end{pmatrix}$ $\\begin{pmatrix} x \\\\\\ y \\\\\\ z \\end{pmatrix}$<br><br>",
	longmcq(opts))
```
:::

::: {.callout-tip collapse="true" title="Lösung"}
(b) $$ \begin{pmatrix}4 & -3 & 2 \\ 0 & 1 & -1 \\ -2 & 3 & 0 \end{pmatrix}\begin{pmatrix}x \\ y \\ z \end{pmatrix} = \begin{pmatrix} 4x & - & 3y & + & 2z \\ & & y & - & z \\ -2x & + & 3y\end{pmatrix}$$
:::



::: {.webex-check .webex-box}
```{r, results='asis', echo=FALSE}
cat("(c) Berechnen Sie <br> <br> $A =\\begin{pmatrix} 3 & -2 & 1 \\\\\\ 0 & 1 & 1 \\\\\\ 4 & -1 & 2 \\end{pmatrix}$ $\\begin{pmatrix} 1 \\\\\\ 2 \\\\\\ -3 \\end{pmatrix} =$<br><br>")
cat("$A = \\biggl($", paste0(fitb(-4, num=TRUE), fitb(-1, num=TRUE), fitb(-4, num=TRUE)), "$\\biggl)$")	
```
:::

::: {.callout-tip collapse="true" title="Lösung"}
(c) $$ \begin{pmatrix} 3 & -2 & 1 \\ 0 & 1 & 1 \\ 4 & -1 & 2\end{pmatrix}\begin{pmatrix}1 \\ 2 \\ -3 \end{pmatrix} = \begin{pmatrix}-4 \\ -1 \\ -4 \end{pmatrix}$$
:::


### Übungen 6 – A3

Es sei die Matrix $A =\begin{pmatrix} 0 & 1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 1 \\ \end{pmatrix}$
gegeben:

::: {.webex-check .webex-box}
```{r, results='asis', echo=FALSE}
opts <- c(
	"$A$ ist nicht invertierbar",
	"$A^{2} = A$",
	answer = "$A = A^{-1}$"
)

cat("(a) Berechnen Sie $A \\cdot A$. Welche Aussage ist korrekt?", longmcq(opts))
```
:::

::: {.callout-tip collapse="true" title="Lösung"}
(a) $$ AA = \begin{pmatrix}0 & 1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 1\end{pmatrix} \begin{pmatrix}0 & 1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 1\end{pmatrix} = \begin{pmatrix}1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{pmatrix} \Rightarrow A^{-1} = A$$ 
Nach Definition ist $A^{-1}$ die Matrix, für die $A \cdot A^{-1}= I$ gilt.
Da hier bereits gilt, erfüllt $A \cdot A= I$  selbst diese Eigenschaft.
Daher ist $A$ seine eigene Inverse.
:::

::: {.webex-check .webex-box}
```{r, results='asis', echo=FALSE}
opts <- c(
	"$BB^{T} =\\begin{pmatrix} 2 & 0 & 2 \\\\\\ 0 & 2 & 0 \\\\\\ 2 & 1 & 2 \\\\\\ \\end{pmatrix}$<br><br>",
	answer = "$BB^{T} =\\begin{pmatrix} 3 & 0 & 2 \\\\\\ 0 & 2 & 0 \\\\\\ 2 & 0 & 2 \\\\\\ \\end{pmatrix}$<br><br>",
	"$BB^{T} =\\begin{pmatrix} 2 & 0 & 2 \\\\\\ 1 & 2 & 0 \\\\\\ 2 & 0 & 2 \\\\\\ \\end{pmatrix}$"
)
cat("(b) Es sei die Matrix $B =\\begin{pmatrix} 1 & 1 & 1 \\\\\\ -1 & 1 & 0 \\\\\\ 1 & 1 & 0 \\\\\\ \\end{pmatrix}$ <br><br>
	gegeben. Berechnen Sie B $\\cdot$ $B^{T}$.<br><br>",
	longmcq(opts))
```
:::

::: {.callout-tip collapse="true" title="Lösung"}
(b) $$ BB^{T}\begin{pmatrix}1 & 1 & 1 \\ -1 & 1 & 0 \\ 1 & 1 & 0 \end{pmatrix} \begin{pmatrix}1 & -1 & 1 \\ 1 & 1 & 1 \\ 1 & 0 & 0\end{pmatrix} = \begin{pmatrix}3 & 0 & 2 \\ 0 & 2 & 0 \\ 2 & 0 & 2\end{pmatrix}$$
:::



